
var ActionTypes  = {
  MOVE_CARD: 'MOVE_CARD',
  ROTATE_CARD: 'ROTATE_CARD',
  RESIZE_CARD: 'RESIZE_CARD',

  ADD_CARD: 'ADD_CARD',
  DELETE_CARD: 'DELETE_CARD',

  SELECT_CARD: 'SELECT_CARD',
  UNSELECT_ALL_CARD: 'UNSELECT_ALL_CARD',
  SELECT_DECK: 'SELECT_DECK',
};

export default ActionTypes;