
var ActionTypes  = {
  SHOW_DECKS_PANE: 'SHOW_DECKS_PANE ',
  TOGGLE_FACE_BACK_IN_PANE: 'TOGGLE_FACE_BACK_IN_PANE',

  MOVE_CARD: 'MOVE_CARD',
  ROTATE_CARD: 'ROTATE_CARD',
  RESIZE_CARD: 'RESIZE_CARD',

  ADD_CARD: 'ADD_CARD',
  DELETE_CARD: 'DELETE_CARD',

  SELECT_CARD: 'SELECT_CARD',
  FLIP_CARD: 'FLIP_CARD',
  UNSELECT_ALL_CARD: 'UNSELECT_ALL_CARD',
  SELECT_DECK: 'SELECT_DECK',
};

export default ActionTypes;